version: '3.7'

volumes:
    prometheus_data: {}
    grafana_data: {}

services:
    sql-collector:
        build:
          context: ./src
          dockerfile: ./SqlCollector/Dockerfile
        volumes:
          - ./config/sql-collector.yaml:/app/sql-collector.yaml

    prometheus:
        image: prom/prometheus:latest
        ports:
            - "9090:9090"
        volumes:
            - ./compose/prometheus:/app.cfg
            - prometheus_data:/prometheus
        extra_hosts:
            - "host.docker.internal:host-gateway"
        command: >-
            --config.file=/app.cfg/prometheus.yml
            --storage.tsdb.path=/prometheus
            --web.console.libraries=/usr/share/prometheus/console_libraries
            --web.console.templates=/usr/share/prometheus/consoles

    grafana:
        image: grafana/grafana:latest
        ports:
            - "3000:3000"
        environment:
            GF_SECURITY_ADMIN_USER: admin
            GF_SECURITY_ADMIN_PASSWORD: monitoring
            GF_PATHS_PROVISIONING: '/app.cfg/provisioning'
        volumes:
            - ./compose/grafana:/app.cfg
            - grafana_data:/var/lib/grafana