Logging:
  LogLevel:
    Default: Information
    Microsoft.AspNetCore: Warning

ConnectionStrings:
  SqlServer: Server=(local);Database=master;User Id=sa;Password=pass1!2@;MultipleActiveResultSets=true;Application Name=SqlCollector;Encrypt=false

SqlMonitoring:
  Groups:
    - SQLServer:Access Methods
    - SQLServer:Databases
    - SQLServer:Deprecated Features
    - SQLServer:General Statistics
    - SQLServer:Latches
    - SQLServer:Locks
    - SQLServer:Memory Manager
    - SQLServer:Plan Cache
    - SQLServer:Resource Pool Stats
    - SQLServer:SQL Statistics
    - SQLServer:Transactions
    - SQLServer:Wait Statistics