global:
  scrape_interval:     5s
  evaluation_interval: 5s

alerting:
  alertmanagers:
  - static_configs:
    - targets:

rule_files:

scrape_configs:
  - job_name: 'sql'
    static_configs:
      - targets: ['sql-collector']
    tls_config:
      insecure_skip_verify: true