{
 "title": "Databases",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "database",
    "query": {
     "query": "label_values(sqlserver_databases_transactions_sec,instance_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total transactions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(sqlserver_databases_transactions_sec{instance_name=\"_Total\"}[$__rate_interval])",
     "legendFormat": "{{instance_name}}"
    }
   ]
  },
  {
   "title": "Compilations per second",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(sqlserver_sql_statistics_sql_compilations_sec[$__rate_interval])",
     "legendFormat": "Compilations"
    },
    {
     "expr": "rate(sqlserver_sql_statistics_sql_re_compilations_sec[$__rate_interval])",
     "legendFormat": "Re-compilations"
    }
   ]
  },
  {
   "title": "Plan cache hit ratio",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "avg(sqlserver_plan_cache_cache_hit_ratio) by (instance_name)",
     "legendFormat": "{{instance_name}}"
    }
   ]
  },
  { "title": "Database: $database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }, "repeat": "database" },
  {
   "title": "Panel Title $database",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(sqlserver_databases_transactions_sec{instance_name=\"$database\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}