{
 "title": "Overview",
 "description": "Key metrics of SQL server",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(sqlserver_resource_pool_stats_cpu_usage_p) by (instance_name)",
     "legendFormat": "{{instance_name}}"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "sum(sqlserver_resource_pool_stats_used_memory_kb) by (instance_name)",
     "legendFormat": "{{instance_name}}"
    }
   ]
  },
  {
   "title": "Disk Reads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(sqlserver_resource_pool_stats_disk_read_bytes_sec[1m])) by (instance_name) ",
     "legendFormat": "{{instance_name}}"
    }
   ]
  },
  {
   "title": "Disk Writes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(sqlserver_resource_pool_stats_disk_write_bytes_sec[1m])) by (instance_name) ",
     "legendFormat": "{{instance_name}}"
    }
   ]
  },
  { "title": "SQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Batch requests/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(sqlserver_sql_statistics_batch_requests_sec[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sqlserver_general_statistics_logical_connections",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}